sudo: required
language: generic
services:
    - docker
before_install:
    - docker build -t mpk/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true  mpk/react-test npm test

after_success:
    - docker build -t praskatti/multi-client ./client
    - docker build -t praskatti/multi-nginx ./nginx
    - docker build -t praskatti/multi-server ./server
    - docker build -t praskatti/multi-worker ./worker

#log in to docker hub
 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

# push images to docker hub

    - docker push  praskatti/multi-client
    - docker push praskatti/multi-nginx
    - docker push   praskatti/multi-server
    - docker push  praskatti/multi-worker
deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker-mpk
    env: MultiDockerMpk-env
    bucket_name: elasticbeanstalk-us-east-1-553203812108
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY        
        

